buildscript {
    repositories {
        maven { url 'https://repo.maven.apache.org/maven2' }
        maven { url 'https://jitpack.io' }
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven { url = 'https://maven.brott.dev/' }
        maven { url 'https://jitpack.io' }
    }
}

repositories {
    mavenCentral()
}